services:
  # Base de datos PostgreSQL
  jbrew-pg-db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    container_name: jbrew-pg-db-container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PGSQL_PORT_PUBLIC}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      #- ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      jbrew-pg-network:
        ipv4_address: 173.21.0.251
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5 # NÃºmero de intentos antes de marcar como no saludable
      start_period: 30s #Espera inicial antes de comenzar a comprobar(Dar tiempo a PostgreSQL inicie)

  jbrew-pg-adminer-db:
      image: adminer
      container_name: jbrew-pg-adminer-db-container
      restart: unless-stopped
  #    restart: always
      ports:
        - 8081:8080
      depends_on:
        - jbrew-pg-db
      networks:
        jbrew-pg-network:
          ipv4_address: 173.21.0.253

  jbrew-pg-admin4-db:
    container_name: jbrew-pgadmin4-container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "adminDB@postgres.org"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - 16543:80
    depends_on:
      - jbrew-pg-db
    networks:
      jbrew-pg-network:
        ipv4_address: 173.21.0.254

networks:
  jbrew-pg-network:
    driver: bridge
    #driver_opts:
    #    parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 173.21.0.0/24
volumes:
  pg-data:
    name: jbrew-pg-data-local
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_DATA_DIR_BD}
      o: bind